name: "Build Docker image"

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  build-docker:
    name: "ğŸ³ Build and publish Docker image"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "â“ Find the release semantic version"
        id: semver
        uses: Steffo99/actions-semver@v0.3.5
        with:
          string: ${{ github.event.release.tag_name }}

      - name: "ğŸ”¨ Setup Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "ğŸ”‘ Login to GitHub Containers"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: RYGhub
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "ğŸ— Build and push the Docker image"
        uses: docker/build-push-action@v3.2.0
        with:
          tags: >-
            ghcr.io/steffo99/greed:${{ steps.semver.outputs.precedence }},
            ghcr.io/steffo99/greed:${{ steps.semver.outputs.core }},
            ghcr.io/steffo99/greed:${{ steps.semver.outputs.pair }},
            ghcr.io/steffo99/greed:${{ steps.semver.outputs.major }},
            ghcr.io/steffo99/greed:latest
          platforms: >-
            linux/amd64
          push: true
